=== milkeg/UnderGradProject/JAVA & PHP - WebService & RMI/RMI/Catalogue1/CatalogueXML/catalogue.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT catalogue (produit)+>
<!ELEMENT produit (nomProduit, quantite, prix, description)>
<!ATTLIST produit categorie (Livre|Nourriture|Vetement|Papeterie|Musique) #REQUIRED>
<!ELEMENT nomProduit (#PCDATA)> 
<!ELEMENT quantite (#PCDATA)>
<!ELEMENT prix (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== milkeg/UnderGradProject/JAVA & PHP - WebService & RMI/RMI/Catalogue1/CatalogueXML/catalogue.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogue SYSTEM "catalogue.dtd">
<catalogue>
	<produit categorie="Livre">
   		<nomProduit>Les Robots</nomProduit>
	    <quantite>12</quantite>
	    <prix>5.2</prix>
	    <description>Livre de Isaac Asimov</description>
  	</produit>
	<produit categorie="Livre">
		<nomProduit>Harry Potter</nomProduit>
	    <quantite>20</quantite>
	    <prix>9.3</prix>
	    <description>Livre de J.K. Rowling</description>
	</produit>
  	<produit categorie="Livre">
    	<nomProduit>Le Seigneur des Anneaux</nomProduit>
    	<quantite>6</quantite>
	    <prix>4.8</prix>
	    <description>Livre de J.R.R Tolkien</description>
	</produit>
	<produit categorie="Livre">
    	<nomProduit>Le Rire du Cyclope</nomProduit>
    	<quantite>23</quantite>
    	<prix>6.4</prix>
    	<description>Livre de Bernard Werber</description>
  	</produit>
  	<produit categorie="Musique">
    	<nomProduit>Ben l'Oncle Soul</nomProduit>
    	<quantite>23</quantite>
    	<prix>17.4</prix>
    	<description>Dernier album de Ben l'Oncle Soul</description>
  	</produit>
</catalogue>

=== milkeg/UnderGradProject/JAVA & PHP - WebService & RMI/RMI/Catalogue2/CatalogueXML/catalogue.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogue SYSTEM "catalogue.dtd">
<catalogue>
	<produit categorie="Musique">
    	<nomProduit>Guitare Folk</nomProduit>
	    <quantite>3</quantite>
	    <prix>138.2</prix>
	    <description>Guitare de marque Guild</description>
  	</produit>
	<produit categorie="Vetement">
		<nomProduit>Chaussures de sport</nomProduit>
	    <quantite>20</quantite>
	    <prix>32.1</prix>
	    <description>Chaussures de tennis rouge</description>
	</produit>
  	<produit categorie="Papeterie">
    	<nomProduit>Stylo BIC</nomProduit>
    	<quantite>45</quantite>
		<prix>1.2</prix>
		<description>Stylo quatre couleurs</description>
	</produit>
	<produit categorie="Nourriture">
    	<nomProduit>Lasagnes au cheval</nomProduit>
    	<quantite>23</quantite>
    	<prix>6.4</prix>
    	<description>Excellentes lasagnes Findus</description>
  	</produit>
</catalogue>
