=== milkeg/UnderGradProject/JAVA & PHP - WebService & RMI/WSBanque/ComptesXML/comptes.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT listeComptes (compte)+>
<!ELEMENT compte (solde)>
<!ATTLIST compte numeroCompte CDATA #REQUIRED
				 password CDATA #REQUIRED>
<!ELEMENT solde (#PCDATA)>

=== milkeg/UnderGradProject/JAVA & PHP - WebService & RMI/WSBanque/ComptesXML/comptes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listeComptes SYSTEM "comptes.dtd" >
<listeComptes>
  <compte numeroCompte="111" password="coucou">
    <solde>100</solde>
  </compte>
  <compte numeroCompte="222" password="coucou">
    <solde>678</solde>
  </compte>
  <compte numeroCompte="333" password="coucou">
    <solde>54</solde>
  </compte>
  <compte numeroCompte="444" password="coucou">
    <solde>29.9</solde>
  </compte>
</listeComptes>
